### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by dexterkawikes** [thesp0nge/owasp-orizon#1]
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOf(Arrays.java:3181)
        at java.util.ArrayList.grow(ArrayList.java:261)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
        at java.util.ArrayList.addAll(ArrayList.java:579)
        at org.owasp.orizon.mirage.java.parser.Nodes.getAllTokens(Nodes.java:164)
        at org.owasp.orizon.mirage.java.parser.Nodes.getAllTokens(Nodes.java:164)
        at org.owasp.orizon.mirage.java.parser.Nodes.getAllTokens(Nodes.java:164)
        at org.owasp.orizon.mirage.java.parser.Nodes.getAllTokens(Nodes.java:164)
        at org.owasp.orizon.mirage.java.parser.Nodes.getAllTokens(Nodes.java:164)
        at org.owasp.orizon.mirage.java.parser.Nodes.getAllTokens(Nodes.java:164)
        at org.owasp.orizon.mirage.java.parser.Nodes.getAllTokens(Nodes.java:164)
        at org.owasp.orizon.mirage.java.parser.Nodes.getAllTokens(Nodes.java:164)
        at org.owasp.orizon.mirage.java.parser.Nodes.getAllTokens(Nodes.java:164)
        at org.owasp.orizon.mirage.java.JavaCollector.inspect(JavaCollector.java:428)
        at org.owasp.orizon.mirage.Modeler.inspect(Modeler.java:162)
        at org.owasp.orizon.mirage.Mirage.start(Mirage.java:288)
        at org.owasp.orizon.mirage.Mirage.process(Mirage.java:191)
        at org.owasp.orizon.mirage.Mirage.exec(Mirage.java:161)
        at org.owasp.orizon.Session.model(Session.java:158)
        at org.owasp.orizon.SkyLine.launch(SkyLine.java:409)
        at org.owasp.orizon.tools.osh.Osh.process(Osh.java:430)
        at org.owasp.orizon.tools.osh.Osh.exec(Osh.java:262)
        at org.owasp.orizon.tools.osh.Osh.shell(Osh.java:229)
        at org.owasp.orizon.tools.osh.Osh.main(Osh.java:135)

**Comment by thesp0nge** [comment]
This part is about the old Orizon implementation. You can try to give more memory to java interpreter
